#!/bin/sh
# make a config drive dir
#   http://pad.lv/1673411
Usage() {
   cat <<EOF
Usage: ${0##*/} outputdir [lxc-container]

create a config drive directory in outputdir.
if lxc-container provided, push the files into /config-drive
EOF
}

if [ "$1" = "--help" ]; then
    Usage; exit 0;
fi
set -e
bdir="$1"
vers="2015-10-15 latest"
hostname="foohost"
for ver in $vers; do
    ddir="$bdir/openstack/$ver"
    mkdir -p "$ddir"
    cat > "$ddir/meta_data.json" <<EOF
{"random_seed": "Zm9vCg==",
 "uuid": "d75e41d8-25be-43d6-b6d5-66db3115eb9f",
 "availability_zone": "nova",
 "hostname": "$hostname"}
EOF
    cat > "$ddir/vendor_data.json" <<EOF
{}
EOF
    cat > "$ddir/user_data" <<"EOF"
#!/bin/sh
now=$(date -R)
read up idle </proc/uptime
echo "$now: HI MOM" | tee /run/greeting.txt
EOF
#    cat > "$ddir/network_data.json" <<EOF
#{
# "links": [
#  {
#   "ethernet_mac_address": "fa:16:3e:b2:dc:83",
#   "id": "tap8b1378a5-50",
#   "mtu": 0,
#   "type": "ovs",
#   "vif_id": "8b1378a5-5016-487f-91c7-a50f35f4ae80"
#  }
# ],
# "networks": [
#  {
#   "id": "network0",
#   "link": "tap8b1378a5-50",
#   "network_id": "db6a8975-5ca2-49d6-8ca7-f8747a163e58",
#   "type": "ipv4_dhcp"
#  }
# ],
# "services": [
#  {"address": "10.245.160.2", "type": "dns"}
# ]
#}
#EOF
done

if [ $# -eq 2 ]; then
    bdir=$( cd "$bdir" && pwd)
    name="$2"
    # lxc file push broken for me now.
    # https://github.com/lxc/lxd/issues/3153
    tar -C "$bdir" -cf - "--transform=s,^.,config-drive," . |
        sudo mount-image-callback lxd:$name -- mchroot tar -C / -xvf -
#    for f in $(find "$bdir/" -type f); do
#       path=${f#${bdir}}
#       tpath="config-drive/$path"
#       echo "pushed $tpath"
#    done
fi
